#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 ikki yamanaka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime

def progress_birthday_date(birthday_date: str):
    try:
        birthday = datetime.date.fromisoformat(birthday_date)
    except ValueError:
        raise ValueError("error")

    today = datetime.date.today()
    if birthday > today:
        raise ValueError("error")

    return (today - birthday).days

def progress_birthday():
    try:
        input_data = sys.stdin.read().strip()
        if not input_data:
            sys.exit(0)
        days_progress = progress_birthday_date(input_data)
        print(days_progress)
        sys.exit(0)

    except ValueError as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    progress_birthday()
