#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 ikki yamanaka
# SPDX-License-Identifier: BSD-3-Clause

import sys
import datetime

def progress_birthday_date(birthday_date: str):
    try:
        birthday = datetime.date.fromisoformat(birthday_date)
    except ValueError:
        raise ValueError("error")

    today = datetime.date.today()
    
    if birthday > today:
        raise ValueError("error")

    difference = today - birthday
    return difference.days

def progress_birthday():
    birthday_date = input()

    try:
        days_progress = progress_birthday_date(birthday_date)
        print(f" {days_progress}")

    except ValueError as e:
        print(f" {e}")

if __name__ == "__main__":
    progress_birthday()
