#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 ikki yamanaka
# SPDX-License-Identifier: BSD-3-Clause

import sys
   
ans = 0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += flout(line)

print(ans)
